/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheImageDialog: typeof import('./components/TheImageDialog.vue')['default']
    TheList: typeof import('./components/TheList.vue')['default']
    TheListItem: typeof import('./components/TheListItem.vue')['default']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
    TheSearch: typeof import('./components/TheSearch.vue')['default']
    ToggleDarkModeButton: typeof import('./components/ToggleDarkModeButton.vue')['default']
  }
}
